version: "3.9"
services:
  lighthousebeacon:
    image: "mragicl/kintsugi-lighthousebeacon:latest"
    ports:
      - "19000:9000"
    volumes:
      - "./data/lighthouse:/var/lib/lighthouse"
      - "./data/app:/data/app"
  lighthousevalidator:
    image: "mragicl/kintsugi-lighthousevalidator:latest"
    volumes:
      - "./data/lighthouse:/var/lib/lighthouse"
      - "./data/app:/data/app"
  geth:
    image: "mragicl/kintsugi-geth:latest"
    ports:
      - "30343:30303"
    volumes:
      - "./data/goethereum:/var/lib/goethereum"
  app:
    image: "mragicl/kintsugi-app:latest"
    volumes:
      - "./data/app:/data/app"
    stdin_open: true
    tty: true
